name: PHP tests
on:
  push:
jobs:
  tests:
    strategy:
      matrix:
        phpversion: [ "8.0", "8.1", "8.2", "8.3", "8.4", "8.5", "latest"]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.phpversion }}-cli
    steps:
      - uses: actions/checkout@v6

      - name: Run tests with PHP
        run: php tests/tests.php
